
apiVersion: v1
kind: Namespace
metadata:
  name: glasswallet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glasswallet-app
  namespace: glasswallet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: glasswallet-app
  template:
    metadata:
      labels:
        app: glasswallet-app
    spec:
      containers:
      - name: glasswallet
        image: glasswallet:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: glasswallet-secrets
              key: database-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: glasswallet-service
  namespace: glasswallet
spec:
  selector:
    app: glasswallet-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: glasswallet-hpa
  namespace: glasswallet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: glasswallet-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
